"""empty message

Revision ID: 1286c3866b74
Revises: 
Create Date: 2020-09-02 20:14:52.252301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1286c3866b74'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cve__history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cve_id', sa.String(length=50), nullable=True),
    sa.Column('last_modified', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('vector', sa.String(length=50), nullable=True),
    sa.Column('impact', sa.Float(), nullable=True),
    sa.Column('cvss', sa.Text(), nullable=True),
    sa.Column('active', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('history')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.VARCHAR(length=20), nullable=True),
    sa.Column('cve_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['cve_id'], ['cve.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cve__history')
    # ### end Alembic commands ###
