"""empty message

Revision ID: 363ae57e3fa7
Revises: e8cf51be9f49
Create Date: 2020-09-02 20:30:51.955919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '363ae57e3fa7'
down_revision = 'e8cf51be9f49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cve_id', sa.String(length=50), nullable=True),
    sa.Column('last_modified', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('vector', sa.String(length=50), nullable=True),
    sa.Column('impact', sa.Float(), nullable=True),
    sa.Column('cvss', sa.Text(), nullable=True),
    sa.Column('active', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history')
    # ### end Alembic commands ###
